sudo: false
dist: trusty
language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"  
  - "2.4"
  - "2.5"
  - "2.6"

cache:
  bundler: true
bundler_args: --without development
before_install:
  - gem update --system || true
  - gem install bundler || gem install bundler -v 1.15
script:
  - bundle exec rake
  - bundle exec rubocop
